# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 'Demo'

steps:
- script: ./mvnw clean
  displayName: 'Clean build env'

- script: ./mvnw package
  displayName: 'Maven package'

- task: Docker@2
  inputs:
    containerRegistry: 'Teco demo env harbor'
    repository: 'demo'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '--build-arg JAR_FILE=target/*.jar'
