# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

variables:
  ACR.Name: 'demo2557dd8ec0'
  ACR.FullName: 'demo2557dd8ec0.azurecr.io'

jobs:
  - job: A
    displayName: Build image and push to Azure registry
    pool:
      name: 'DemoAzurePool'
    steps:
#    - script: echo $(ACR.FullName)
#    - script: ./mvnw clean
#      displayName: 'Clean build env'
#    - script: ./mvnw package
#      displayName: 'Maven package'
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        goals: 'test'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false

    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        options: '-DskipTests'
        publishJUnitResults: false
        javaHomeOption: 'JDKVersion'
        mavenVersionOption: 'Default'
        mavenAuthenticateFeed: false
        effectivePomSkip: false
        sonarQubeRunAnalysis: false
    - task: Docker@2
      displayName: 'Build container'
      inputs:
        containerRegistry: 'DemoDevRegistry'
        repository: 'demo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '--build-arg JAR_FILE=target/*.jar'

    - task: Docker@2
      displayName: 'Push container to ACR'
      inputs:
        containerRegistry: 'DemoDevRegistry'
        repository: 'demo'
        command: 'push'
  - job: B
    displayName: Upload image to prod registry
    dependsOn: A
    pool: Demo
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DemoDevRegistry'
        command: 'login'
    - script: docker pull $(ACR.FullName)/demo:$(Build.BuildId)
    - script: docker tag $(ACR.FullName)/demo:$(Build.BuildId) harbor.svc.tieto1.1-4.fi.teco.online/demo/demo:$(Build.BuildId)
    - task: Docker@2
      inputs:
        containerRegistry: 'Teco demo env harbor'
        repository: 'demo/demo'
        command: 'push'
  - job: C
    displayName: Create and publish artifacts
    dependsOn: A
    pool:
      name: 'DemoAzurePool'
    steps:
    - task: CmdLine@1
      displayName: 'Set image version in dev deployment.yaml'
      inputs:
        filename: /bin/bash
        arguments: '-c "awk ''{gsub(\"DEMO_IMAGE\", \"$(ACR.FullName)/demo:$(Build.BuildId)\", $0); print}'' deployment.yaml >  $(build.artifactstagingdirectory)/deployment-dev.yaml"'
    - task: CmdLine@1
      displayName: 'Set image version in prod deployment.yaml'
      inputs:
        filename: /bin/bash
        arguments: '-c "awk ''{gsub(\"DEMO_IMAGE\", \"harbor.svc.tieto1.1-4.fi.teco.online/demo/demo:$(Build.BuildId)\", $0); print}'' deployment.yaml > $(build.artifactstagingdirectory)/deployment-prod.yaml"'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
