# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master

variables:
  ACR.Name: '{{#toAlphaNumericString DemoDevRegistry 46}}{{/toAlphaNumericString}}{{#shortGuid}}{{/shortGuid}}'

jobs:
  - job: A
    displayName: Build image and push to Azure registry
    pool:
      name: 'DemoAzurePool'
    steps:
    - script: echo $(ACR.Name)
    - script: ./mvnw clean
      displayName: 'Clean build env'
    - script: ./mvnw package
      displayName: 'Maven package'


    - task: Docker@2
      displayName: 'Build container'
      inputs:
        containerRegistry: 'DemoDevRegistry'
        repository: 'demo'
        command: 'build'
        Dockerfile: '**/Dockerfile'
        arguments: '--build-arg JAR_FILE=target/*.jar'

    - task: Docker@2
      displayName: 'Push container to harbor'
      inputs:
        containerRegistry: 'DemoDevRegistry'
        repository: 'demo'
        command: 'push'
  - job: B
    displayName: Upload image to prod registry
    dependsOn: A
    pool: Demo
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'DemoDevRegistry'
        command: 'login'
    - script: docker pull $(ACR.Name)/demo:$(Build.BuildId)
    - script: docker tag $(ACR.Name)/demo:$(Build.BuildId) harbor.svc.tieto1.1-4.fi.teco.online/demo/demo:$(Build.BuildId)
    - task: Docker@2
      inputs:
        containerRegistry: 'Teco demo env harbor'
        repository: 'demo/demo'
        command: 'push'
  - job: C
    displayName: Create and public artifacts
    dependsOn: A
    pool:
      name: 'DemoAzurePool'
    steps:
    - task: CmdLine@1
      displayName: 'Set image version in deployment.yaml'
      inputs:
        filename: /bin/bash
        arguments: '-c "awk ''{gsub(\"DEMO_IMAGE\", \"harbor.svc.tieto1.1-4.fi.teco.online/demo/demo:$(Build.BuildId)\", $0); print}'' deployment.yaml > $(build.artifactstagingdirectory)/deployment.yaml"'
    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'